version: '3.8'
services:
  www:
    image: sameeksha1384/php:apache:latest
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"  # sync persistent SQL files with container

  phpmyadmin:
    image: sameeksha1384/php:apache:latest
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
